# Generated by Django 4.1.6 on 2023-02-04 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
            ],
        ),
        migrations.AlterField(
            model_name='tracking',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package', to='tracking.package', verbose_name='paquete'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='type_tracking',
            field=models.CharField(choices=[('I', 'Inicial'), ('M', 'Marcha'), ('C', 'Final')], max_length=10, verbose_name='tipo de rastreo'),
        ),
    ]
