# Generated by Django 4.1.6 on 2023-02-04 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_remove_tracking_status_remove_tracking_type_tracking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='email_receiver',
            field=models.EmailField(default='', max_length=254, verbose_name='Correo'),
        ),
    ]
